CREATE TABLE `USER` (
	`id`	VARCHAR(30)	NOT NULL,
	`password`	VARCHAR(30)	NOT NULL,
	`name`	VARCHAR(30)	NOT NULL,
	`email`	VARCHAR(30)	NOT NULL,
	`phone`	VARCHAR(30)	NOT NULL,
	`address`	VARCHAR(100)	NOT NULL,
	`grade`	VARCHAR(10)	NOT NULL	COMMENT '기업, 약사, 관리자',
	`role`	VARCHAR(10)	NOT NULL	COMMENT '회원, 약사,관리자',
	`status`	VARCHAR(1)	NOT NULL,
	`enrollDate`	DATE	NOT NULL,
	`modifyDate`	DATE	NOT NULL,
	`mstatus`	VARCHAR(1)	NOT NULL	COMMENT '일반'
);

CREATE TABLE `PHARMACY` (
	`pharmNo`	INT	NOT NULL,
	`pharmaddr`	VARCHAR(100)	NOT NULL,
	`pharmName`	VARCHAR(30)	NOT NULL,
	`pharmTel`	VARCHAR(30)	NOT NULL,
	`pharmPictureUrl`	text	NULL,
	`pharmOp1`	VARCHAR(30)	NOT NULL,
	`pharmOp2`	VARCHAR(30)	NOT NULL,
	`pharmOp3`	VARCHAR(30)	NOT NULL,
	`pharmOp4`	VARCHAR(30)	NOT NULL,
	`pharmOp5`	VARCHAR(30)	NOT NULL,
	`pharmOp6`	VARCHAR(30)	NOT NULL,
	`pharmLati`	VARCHAR(30)	NOT NULL,
	`pharmLong`	VARCHAR(30)	NOT NULL,
	`reviewCount`	INT(11)	NOT NULL,
	`favCount`	INT(11)	NOT NULL,
	`pharmRating`	DECIMAL(2, 1)	NOT NULL,
	`status`	VARCHAR(1)	NOT NULL	COMMENT '일반'
);

CREATE TABLE `ORDERS` (
	`oNo`	BIGINT(20)	NOT NULL,
	`id`	VARCHAR(30)	NOT NULL,
	`pNo`	INT	NOT NULL,
	`pName`	VARCHAR(100)	NOT NULL,
	`payMethod`	VARCHAR(50)	NOT NULL,
	`totalPrice`	INT(10)	NOT NULL,
	`requests`	VARCHAR(100)	NULL,
	`createdDate`	TIMESTAMP	NOT NULL,
	`modifiedDate`	TIMESTAMP	NOT NULL,
	`status`	VARCHAR(1)	NOT NULL
);

CREATE TABLE `CARTS` (
	`cartNo`	INT	NOT NULL,
	`id`	VARCHAR(30)	NOT NULL,
	`pNo`	INT	NOT NULL,
	`pName`	VARCHAR(100)	NOT NULL,
	`Quantity`	INT	NOT NULL,
	`totalPrice`	INT	NOT NULL,
	`createdDate`	timestamp	NOT NULL,
	`modifiedDate`	timestamp	NOT NULL,
	`status`	VARCHAR(1)	NOT NULL
);

CREATE TABLE `MEDICINE_REVIEWS` (
	`mereviewid`	INT	NOT NULL,
	`id2`	VARCHAR(30)	NOT NULL,
	`itemName`	VARCHAR(500)	NOT NULL,
	`rating`	INT	NOT NULL,
	`content`	VARCHAR(1000)	NULL,
	`reviewPicture`	text	NULL	COMMENT '영수증, 제품사진',
	`readcount`	int	NOT NULL,
	`attachcount`	VARCHAR(255)	NOT NULL,
	`createdDate`	timestamp	NOT NULL,
	`modifyDate`	timestamp	NOT NULL,
	`status`	VARCHAR(1)	NOT NULL,
	`thumbcount`	INT	NOT NULL
);

CREATE TABLE `MyAidKit` (
	`id`	VARCHAR(30)	NOT NULL,
	`itemName`	VARCHAR(255)	NOT NULL,
	`quantity`	INT	NOT NULL,
	`experationDate`	DATE	NOT NULL,
	`createdDate`	timestamp	NOT NULL,
	`modifiedDate`	timestamp	NOT NULL,
	`status`	VARCHAR(1)	NOT NULL
);

CREATE TABLE `QANDA` (
	`boardNo`	INT	NOT NULL,
	`id`	VARCHAR(30)	NOT NULL,
	`title`	VARCHAR(100)	NOT NULL,
	`content`	VARCHAR(500)	NOT NULL,
	`views`	INT	NOT NULL,
	`createdDate`	TIMESTAMP	NOT NULL,
	`modifiedDate`	TIMESTAMP	NOT NULL,
	`status`	VARCHAR(1)	NOT NULL
);

CREATE TABLE `REPLY_QANDA` (
	`rq_id`	INT	NOT NULL,
	`boardNo`	INT	NOT NULL,
	`id`	VARCHAR(30)	NOT NULL,
	`content`	VARCHAR(500)	NOT NULL,
	`createdDate`	TIMESTAMP	NOT NULL,
	`modifiedDate`	TIMESTAMP	NOT NULL,
	`status`	VARCHAR(1)	NOT NULL
);

CREATE TABLE `NEWS` (
	`newsNo`	INT	NOT NULL,
	`title`	VARCHAR(100)	NOT NULL,
	`content`	VARCHAR(500)	NOT NULL,
	`newsImgUrl`	text	NOT NULL,
	`mnewsImgUrl`	text	NOT NULL,
	`views`	INT	NOT NULL,
	`createdDate`	TIMESTAMP	NOT NULL,
	`modifiedDate`	TIMESTAMP	NOT NULL,
	`status`	VARCHAR(1)	NOT NULL
);

CREATE TABLE `MEDICINE` (
	`itemSeq`	INT	NOT NULL,
	`itemName`	VARCHAR(500)	NOT NULL,
	`efcyQesitm`	VARCHAR(500)	NOT NULL,
	`useMethodQesitm`	VARCHAR(500)	NOT NULL,
	`atpnWarnQesitm`	VARCHAR(500)	NOT NULL,
	`atpnQesitm`	VARCHAR(255)	NOT NULL,
	`intrcQesitm`	VARCHAR(500)	NOT NULL,
	`seQesitm`	VARCHAR(500)	NOT NULL,
	`depositMethodQesitm`	VARCHAR(500)	NOT NULL,
	`itemImage`	text	NOT NULL,
	`PROHBT_CONTENT`	VARCHAR(500)	NOT NULL	COMMENT 'DUR',
	`TYPE_NAME`	VARCHAR(10)	NOT NULL	COMMENT 'DUR',
	`PBANC_CONT`	VARCHAR(500)	NOT NULL	COMMENT 'DUR',
	`PBNAC_DIVS_NM`	VARCHAR(255)	NOT NULL	COMMENT 'Safe',
	`CHRG_DEP`	VARCHAR(100)	NOT NULL	COMMENT 'Safe',
	`createdDate`	TIMESTAMP	NOT NULL,
	`modifiedDate`	TIMESTAMP	NOT NULL,
	`status`	VARCHAR(1)	NOT NULL
);

CREATE TABLE `PHARMACY_REVIEWS` (
	`phreviewid`	INT	NOT NULL,
	`pharmNo`	INT	NOT NULL,
	`id2`	VARCHAR(30)	NOT NULL,
	`rating`	VARCHAR(255)	NOT NULL,
	`content`	VARCHAR(1000)	NULL,
	`reviewPicture`	text	NULL,
	`readcount`	int	NOT NULL,
	`attachcount`	int	NOT NULL,
	`thumbcount`	INT	NOT NULL,
	`createdDate`	timestamp	NOT NULL,
	`modifiedDate`	timestamp	NOT NULL,
	`status`	VARCHAR(1)	NOT NULL
);

CREATE TABLE `REPLY_PHREVIEWS` (
	`rq_id`	INT	NOT NULL,
	`phreviewid`	INT	NOT NULL,
	`pharmNo`	INT	NOT NULL,
	`id2`	VARCHAR(30)	NOT NULL,
	`content`	VARCHAR(500)	NOT NULL,
	`createdDate`	TIMESTAMP	NOT NULL,
	`modifiedDate`	TIMESTAMP	NOT NULL,
	`status`	VARCHAR(1)	NOT NULL
);

CREATE TABLE `REPLY_MEREVIEWS` (
	`rq_id`	INT	NOT NULL,
	`mereviewid`	INT	NOT NULL,
	`id2`	VARCHAR(30)	NOT NULL,
	`itemName`	VARCHAR(500)	NOT NULL,
	`content`	VARCHAR(500)	NOT NULL,
	`createdDate`	TIMESTAMP	NOT NULL,
	`modifiedDate`	TIMESTAMP	NOT NULL,
	`status`	VARCHAR(1)	NOT NULL
);

CREATE TABLE `HEALTH_FUNCTIONAL_FOOD` (
	`pNo`	INT	NOT NULL,
	`pName`	VARCHAR(100)	NOT NULL,
	`pPrice`	INT	NOT NULL,
	`pImgURL`	text	NOT NULL,
	`pMaker`	VARCHAR(1000)	NOT NULL,
	`pType`	VARCHAR(1000)	NOT NULL,
	`pInfo`	VARCHAR(1000)	NOT NULL,
	`category1`	VARCHAR(1000)	NOT NULL,
	`category2`	VARCHAR(1000)	NOT NULL,
	`category3`	VARCHAR(1000)	NULL,
	`category4`	VARCHAR(1000)	NULL
);

CREATE TABLE `MEDICINE_ATTACH_FILE` (
	`fNo`	INT	NOT NULL,
	`mereviewid`	INT	NOT NULL,
	`id2`	VARCHAR(30)	NOT NULL,
	`itemName`	VARCHAR(500)	NOT NULL,
	`origianl_filename`	VARCHAR(200)	NOT NULL,
	`renamed_filename`	VARCHAR(200)	NOT NULL,
	`createDate`	TIMESTAMP	NOT NULL
);

CREATE TABLE `PHARMACY_ATTACH_FILE` (
	`fNo`	INT	NOT NULL,
	`phreviewid`	INT	NOT NULL,
	`pharmNo`	INT	NOT NULL,
	`id2`	VARCHAR(30)	NOT NULL,
	`origianl_filename`	VARCHAR(200)	NOT NULL,
	`renamed_filename`	VARCHAR(200)	NOT NULL,
	`createDate`	TIMESTAMP	NOT NULL
);

CREATE TABLE `BOARD_ATTACH_FILE` (
	`fNo`	INT	NOT NULL,
	`boardNo`	INT	NOT NULL,
	`id`	VARCHAR(30)	NOT NULL,
	`origianl_filename`	VARCHAR(200)	NOT NULL,
	`renamed_filename`	VARCHAR(200)	NOT NULL,
	`createDate`	TIMESTAMP	NOT NULL
);

ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`id`
);

ALTER TABLE `PHARMACY` ADD CONSTRAINT `PK_PHARMACY` PRIMARY KEY (
	`pharmNo`
);

ALTER TABLE `ORDERS` ADD CONSTRAINT `PK_ORDERS` PRIMARY KEY (
	`oNo`,
	`id`,
	`pNo`,
	`pName`
);

ALTER TABLE `CARTS` ADD CONSTRAINT `PK_CARTS` PRIMARY KEY (
	`cartNo`,
	`id`,
	`pNo`,
	`pName`
);

ALTER TABLE `MEDICINE_REVIEWS` ADD CONSTRAINT `PK_MEDICINE_REVIEWS` PRIMARY KEY (
	`mereviewid`,
	`id2`,
	`itemName`
);

ALTER TABLE `MyAidKit` ADD CONSTRAINT `PK_MYAIDKIT` PRIMARY KEY (
	`id`,
	`itemName`
);

ALTER TABLE `QANDA` ADD CONSTRAINT `PK_QANDA` PRIMARY KEY (
	`boardNo`,
	`id`
);

ALTER TABLE `REPLY_QANDA` ADD CONSTRAINT `PK_REPLY_QANDA` PRIMARY KEY (
	`rq_id`,
	`boardNo`,
	`id`
);

ALTER TABLE `NEWS` ADD CONSTRAINT `PK_NEWS` PRIMARY KEY (
	`newsNo`
);

ALTER TABLE `MEDICINE` ADD CONSTRAINT `PK_MEDICINE` PRIMARY KEY (
	`itemSeq`,
	`itemName`
);

ALTER TABLE `PHARMACY_REVIEWS` ADD CONSTRAINT `PK_PHARMACY_REVIEWS` PRIMARY KEY (
	`phreviewid`,
	`pharmNo`,
	`id2`
);

ALTER TABLE `REPLY_PHREVIEWS` ADD CONSTRAINT `PK_REPLY_PHREVIEWS` PRIMARY KEY (
	`rq_id`,
	`phreviewid`,
	`pharmNo`,
	`id2`
);

ALTER TABLE `REPLY_MEREVIEWS` ADD CONSTRAINT `PK_REPLY_MEREVIEWS` PRIMARY KEY (
	`rq_id`,
	`mereviewid`,
	`id2`,
	`itemName`
);

ALTER TABLE `HEALTH_FUNCTIONAL_FOOD` ADD CONSTRAINT `PK_HEALTH_FUNCTIONAL_FOOD` PRIMARY KEY (
	`pNo`,
	`pName`
);

ALTER TABLE `MEDICINE_ATTACH_FILE` ADD CONSTRAINT `PK_MEDICINE_ATTACH_FILE` PRIMARY KEY (
	`fNo`,
	`mereviewid`,
	`id2`,
	`itemName`
);

ALTER TABLE `PHARMACY_ATTACH_FILE` ADD CONSTRAINT `PK_PHARMACY_ATTACH_FILE` PRIMARY KEY (
	`fNo`,
	`phreviewid`,
	`pharmNo`,
	`id2`
);

ALTER TABLE `BOARD_ATTACH_FILE` ADD CONSTRAINT `PK_BOARD_ATTACH_FILE` PRIMARY KEY (
	`fNo`,
	`boardNo`,
	`id`
);

ALTER TABLE `ORDERS` ADD CONSTRAINT `FK_USER_TO_ORDERS_1` FOREIGN KEY (
	`id`
)
REFERENCES `USER` (
	`id`
);

ALTER TABLE `ORDERS` ADD CONSTRAINT `FK_HEALTH_FUNCTIONAL_FOOD_TO_ORDERS_1` FOREIGN KEY (
	`pNo`
)
REFERENCES `HEALTH_FUNCTIONAL_FOOD` (
	`pNo`
);

ALTER TABLE `ORDERS` ADD CONSTRAINT `FK_HEALTH_FUNCTIONAL_FOOD_TO_ORDERS_2` FOREIGN KEY (
	`pName`
)
REFERENCES `HEALTH_FUNCTIONAL_FOOD` (
	`pName`
);

ALTER TABLE `CARTS` ADD CONSTRAINT `FK_USER_TO_CARTS_1` FOREIGN KEY (
	`id`
)
REFERENCES `USER` (
	`id`
);

ALTER TABLE `CARTS` ADD CONSTRAINT `FK_HEALTH_FUNCTIONAL_FOOD_TO_CARTS_1` FOREIGN KEY (
	`pNo`
)
REFERENCES `HEALTH_FUNCTIONAL_FOOD` (
	`pNo`
);

ALTER TABLE `CARTS` ADD CONSTRAINT `FK_HEALTH_FUNCTIONAL_FOOD_TO_CARTS_2` FOREIGN KEY (
	`pName`
)
REFERENCES `HEALTH_FUNCTIONAL_FOOD` (
	`pName`
);

ALTER TABLE `MEDICINE_REVIEWS` ADD CONSTRAINT `FK_USER_TO_MEDICINE_REVIEWS_1` FOREIGN KEY (
	`id2`
)
REFERENCES `USER` (
	`id`
);

ALTER TABLE `MEDICINE_REVIEWS` ADD CONSTRAINT `FK_MEDICINE_TO_MEDICINE_REVIEWS_1` FOREIGN KEY (
	`itemName`
)
REFERENCES `MEDICINE` (
	`itemName`
);

ALTER TABLE `MyAidKit` ADD CONSTRAINT `FK_USER_TO_MyAidKit_1` FOREIGN KEY (
	`id`
)
REFERENCES `USER` (
	`id`
);

ALTER TABLE `MyAidKit` ADD CONSTRAINT `FK_MEDICINE_TO_MyAidKit_1` FOREIGN KEY (
	`itemName`
)
REFERENCES `MEDICINE` (
	`itemName`
);

ALTER TABLE `QANDA` ADD CONSTRAINT `FK_USER_TO_QANDA_1` FOREIGN KEY (
	`id`
)
REFERENCES `USER` (
	`id`
);

ALTER TABLE `REPLY_QANDA` ADD CONSTRAINT `FK_QANDA_TO_REPLY_QANDA_1` FOREIGN KEY (
	`boardNo`
)
REFERENCES `QANDA` (
	`boardNo`
);

ALTER TABLE `REPLY_QANDA` ADD CONSTRAINT `FK_QANDA_TO_REPLY_QANDA_2` FOREIGN KEY (
	`id`
)
REFERENCES `QANDA` (
	`id`
);

ALTER TABLE `PHARMACY_REVIEWS` ADD CONSTRAINT `FK_PHARMACY_TO_PHARMACY_REVIEWS_1` FOREIGN KEY (
	`pharmNo`
)
REFERENCES `PHARMACY` (
	`pharmNo`
);

ALTER TABLE `PHARMACY_REVIEWS` ADD CONSTRAINT `FK_USER_TO_PHARMACY_REVIEWS_1` FOREIGN KEY (
	`id2`
)
REFERENCES `USER` (
	`id`
);

ALTER TABLE `REPLY_PHREVIEWS` ADD CONSTRAINT `FK_PHARMACY_REVIEWS_TO_REPLY_PHREVIEWS_1` FOREIGN KEY (
	`phreviewid`
)
REFERENCES `PHARMACY_REVIEWS` (
	`phreviewid`
);

ALTER TABLE `REPLY_PHREVIEWS` ADD CONSTRAINT `FK_PHARMACY_REVIEWS_TO_REPLY_PHREVIEWS_2` FOREIGN KEY (
	`pharmNo`
)
REFERENCES `PHARMACY_REVIEWS` (
	`pharmNo`
);

ALTER TABLE `REPLY_PHREVIEWS` ADD CONSTRAINT `FK_PHARMACY_REVIEWS_TO_REPLY_PHREVIEWS_3` FOREIGN KEY (
	`id2`
)
REFERENCES `PHARMACY_REVIEWS` (
	`id2`
);

ALTER TABLE `REPLY_MEREVIEWS` ADD CONSTRAINT `FK_MEDICINE_REVIEWS_TO_REPLY_MEREVIEWS_1` FOREIGN KEY (
	`mereviewid`
)
REFERENCES `MEDICINE_REVIEWS` (
	`mereviewid`
);

ALTER TABLE `REPLY_MEREVIEWS` ADD CONSTRAINT `FK_MEDICINE_REVIEWS_TO_REPLY_MEREVIEWS_2` FOREIGN KEY (
	`id2`
)
REFERENCES `MEDICINE_REVIEWS` (
	`id2`
);

ALTER TABLE `REPLY_MEREVIEWS` ADD CONSTRAINT `FK_MEDICINE_REVIEWS_TO_REPLY_MEREVIEWS_3` FOREIGN KEY (
	`itemName`
)
REFERENCES `MEDICINE_REVIEWS` (
	`itemName`
);

ALTER TABLE `MEDICINE_ATTACH_FILE` ADD CONSTRAINT `FK_MEDICINE_REVIEWS_TO_MEDICINE_ATTACH_FILE_1` FOREIGN KEY (
	`mereviewid`
)
REFERENCES `MEDICINE_REVIEWS` (
	`mereviewid`
);

ALTER TABLE `MEDICINE_ATTACH_FILE` ADD CONSTRAINT `FK_MEDICINE_REVIEWS_TO_MEDICINE_ATTACH_FILE_2` FOREIGN KEY (
	`id2`
)
REFERENCES `MEDICINE_REVIEWS` (
	`id2`
);

ALTER TABLE `MEDICINE_ATTACH_FILE` ADD CONSTRAINT `FK_MEDICINE_REVIEWS_TO_MEDICINE_ATTACH_FILE_3` FOREIGN KEY (
	`itemName`
)
REFERENCES `MEDICINE_REVIEWS` (
	`itemName`
);

ALTER TABLE `PHARMACY_ATTACH_FILE` ADD CONSTRAINT `FK_PHARMACY_REVIEWS_TO_PHARMACY_ATTACH_FILE_1` FOREIGN KEY (
	`phreviewid`
)
REFERENCES `PHARMACY_REVIEWS` (
	`phreviewid`
);

ALTER TABLE `PHARMACY_ATTACH_FILE` ADD CONSTRAINT `FK_PHARMACY_REVIEWS_TO_PHARMACY_ATTACH_FILE_2` FOREIGN KEY (
	`pharmNo`
)
REFERENCES `PHARMACY_REVIEWS` (
	`pharmNo`
);

ALTER TABLE `PHARMACY_ATTACH_FILE` ADD CONSTRAINT `FK_PHARMACY_REVIEWS_TO_PHARMACY_ATTACH_FILE_3` FOREIGN KEY (
	`id2`
)
REFERENCES `PHARMACY_REVIEWS` (
	`id2`
);

ALTER TABLE `BOARD_ATTACH_FILE` ADD CONSTRAINT `FK_QANDA_TO_BOARD_ATTACH_FILE_1` FOREIGN KEY (
	`boardNo`
)
REFERENCES `QANDA` (
	`boardNo`
);

ALTER TABLE `BOARD_ATTACH_FILE` ADD CONSTRAINT `FK_QANDA_TO_BOARD_ATTACH_FILE_2` FOREIGN KEY (
	`id`
)
REFERENCES `QANDA` (
	`id`
);

